---
title: "data_wrangling_part2"
author: "cathy"
date: "2024-10-10"
output: github_document
---
load the package need for this one
```{r}
library(tidyverse)
library(rvest)
library(httr)
```

now the data has been imported
```{r}
 url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

 drug_use_html = read_html(url)
```


Get the pieces i actually need.
```{r}
  marj_use_df =
    drug_use_html |> 
    html_table() |> 
    first() |> 
    slice(-1)
```

Learning assessment

```{r}
 url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
 cost_living_html = read_html(url)
 
 cost_living_df = 
   cost_living_html |> 
   html_table()
```

also can be combine to one step
```{r}
 cost_living_df = 
    read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |> 
   html_table() |> 
   first() # make first row the name
```


## CSS Selectors!!
```{r}
 swm_url = "https://www.imdb.com/list/ls070150896/"

 swm_html = read_html(swm_url)
```

```{r}
swm_title_vec = 
 swm_html |> 
  html_elements(".ipc-title-link-wrapper.ipc-title__text") |> 
  html_text()

swm_runtime_vec = 
 swm_html |> 
  html_elements(".dli-title-metadata-item:nth-child(2)") |> 
  html_text()
 
 swm_score_vec = 
  swm_html |> 
  html_elements(".ipc-rating-star--rating") |> 
  html_text()
```

## Use API

get water data
```{r}
 nyc_water = 
   GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
   content() # show as a table
```


Get BRFSS data

```{r}
 BRFSS_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |>  # increase the row to 5000, or it will only have 1000
 content()
```


Pokemon API

```{r}
 pokemon = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |> 
  content()
```

```{r}
pokemon$height
pokemon$abilities
```



